geprap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('geprapapp.urls')),
    path('tienda/', include('tienda.urls')),
    path('carrito/', include('carrito.urls')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

geprapapp/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name= "geprapapp"
urlpatterns = [
    path('', views.index, name = "index"),

    #Login----------------------------------------------------------------------------------------
    path('loginFormulario/', views.loginFormulario, name="loginFormulario" ),
    path('login/', views.login, name="login" ),
    path('logout/', views.logout, name="logout" ),
     
    #Restablecer contraseña------------------------------------------------------------------------
    path('solicitudRestablecer/',views.solicitudRestablecer, name="solicitudRestablecer"),
    path('restablecer/',views.restablecerContrasena, name="restablecerContrasena"), 
    path('restablecerContrasena/<int:id>',views.cambiarContrasena, name="cambiarContrasena"),
    path('cambiarClave/',views.cambiarClave, name="cambiarClave"),

    # Usuarios--------------------------------------------------------------------------------------
    path('usuarios/', views.listaUsuarios, name="listarUsuarios"),
    path('formularioUsuario/', views.formularioUsuario, name="formularioUsuario"),
    path('guardarUsuario/',views.guardarUsuario, name="guardarUsuario"),
    path('edicionUsuario/<id>', views.edicionUsuario,name="edicionUsuario"),
    path('editarUsuario/', views.editarUsuario, name="editarUsuario"),
    path('eliminarUsuario/<id>', views.eliminarUsuario, name="eliminarUsuario"),
    path('buscarUsuario/', views.buscarUsuario, name="buscarUsuario"), 

    #Registrar cliente-------------------------------------------------------------------------------
    path('formularioRegistro/', views.ClienteFormulario, name="formularioRegistro"),
    path('RegistroCliente/',views.RegistroCliente, name="RegistroCliente"),

    # Categoría--------------------------------------------------------------------------------------
    path('categorias/', views.listaCategoria, name="listarCategoria"),
    path('formularioCategoria/', views.formularioCategoria, name="formularioCategoria"),
    path('guardarCategoria/',views.guardarCategoria, name="guardarCategoria"),
    path('edicionCategoria/<id>', views.edicionCategoria, name="edicionCategoria"),
    path('editarCategoria/', views.editarCategoria, name="editarCategoria"),
    path('eliminarCategoria/<id>', views.eliminarCategoria, name="eliminarCategoria"),
    path('buscarCategoria/', views.buscarCategoria, name="buscarCategoria"),

    # Productos----------------------------------------------------------------------------------------
    path('productos/', views.listaProducto, name="listarProductos"),
    path('formularioProducto/', views.formularioProducto, name="formularioProducto"),
    path('guardarProducto/',views.guardarProducto, name="guardarProducto"),
    path('edicionProducto/<id>', views.editarProducto, name="edicionProducto"),
    path('editarProducto/', views.editarProducto, name="editarProducto"),
    path('eliminarProducto/<id>', views.eliminarProducto, name="eliminarProducto"),
    path('buscarProducto/', views.buscarProducto, name="buscarProducto"),
    
    # Servicio------------------------------------------------------------------------------------------
    path('servicios/', views.listaServicio, name="listarServicio"),
    path('formularioServicio/', views.formularioServicio, name="formularioServicio"),
    path('guardarServicio/',views.guardarServicio, name="guardarServicio"),
    path('edicionServicio/<id>', views.edicionServicio, name="edicionServicio"),
    path('editarServicio/', views.editarServicio, name="editarServicio"),
    path('eliminarServicio/<id>', views.eliminarServicio, name="eliminarServicio"),
    path('buscarServicio/', views.buscarServicio, name="buscarServicio"),

    # Pedidos--------------------------------------------------------------------------------------------
    
    
    path('pedidos/', views.listaPedido, name="listarPedidos"),
    path('formularioPedido/', views.formularioPedido, name="formularioPedido"),
    path('guardarPedido/',views.guardarPedido, name="guardarPedido"),
    path('edicionPedido/<id>', views.edicionPedido, name="edicionPedido"),
    path('editarPedido/', views.editarPedido, name="editarPedido"),
    path('eliminarPedido/<id>', views.eliminarPedido, name="eliminarPedido"),
    path('buscarPedido/', views.buscarPedido, name="buscarPedido"),

    # DetallePedidos---------------------------------------------------------------------------------------
    path('DetallePedidos/', views.listaDetallePedido, name="listarDetallePedidos"),
    path('formularioDetallePedido/', views.formularioDetallePedido, name="formularioDetallePedido"),
    path('guardarDetallePedido/',views.guardarDetallePedido, name="guardarDetallePedido"),
    path('edicionDetallePedido/<id>', views.edicionDetallePedido, name="edicionDetallePedido"),
    path('editarDetallePedido/', views.editarDetallePedido, name="editarDetallePedido"),
    path('eliminarDetallePedido/<id>', views.eliminarDetallePedido, name="eliminarDetallePedido"),
    path('buscarDetallePedido/', views.buscarDetallePedido, name="buscarDetallePedido"),

    # Agenda-------------------------------------------------------------------------------------------------
    path('agenda/', views.listaAgenda, name="listarAgenda"),
    path('formularioAgenda/', views.formularioAgenda, name="formularioAgenda"),
    path('guardarAgenda/',views.guardarAgenda, name="guardarAgenda"),
    path('edicionAgenda/<id>', views.edicionAgenda, name="edicionAgenda"),
    path('editarAgenda/', views.editarAgenda, name="editarAgenda"),
    path('eliminarAgenda/<id>', views.eliminarAgenda, name="eliminarAgenda"),
    path('buscarAgenda/', views.buscarAgenda, name="buscarAgenda"),

    # Metodo_Pago--------------------------------------------------------------------------------------------
    path('metodosPago/', views.listaMetodoPago, name="listarMetodoPago"),
    path('formularioMetodoPago/', views.formularioMetodoPago, name="formularioMetodoPago"),
    path('guardarMetodoPago/',views.guardarMetodoPago, name="guardarMetodoPago"),
    path('edicionMetodoPago/<id>', views.edicionMetodoPago, name="edicionMetodoPago"),
    path('editarMetodoPago/', views.editarMetodoPago, name="editarMetodoPago"),
    path('eliminarMetodoPago/<id>', views.eliminarMetodoPago, name="eliminarMetodoPago"),
    path('buscarMetodoPago/', views.buscarMetodoPago, name="buscarMetodoPago"),

    # Pagos--------------------------------------------------------------------------------------------------
    path('pagos/', views.listaPagos, name="listarPagos"),
    path('formularioPagos/', views.formularioPagos, name="formularioPagos"),
    path('guardarPagos/',views.guardarPagos, name="guardarPago"),
    path('edicionPago/<id>', views.edicionPago, name="edicionPago"),
    path('editarPago/', views.editarPago, name="editarPago"),
    path('eliminarPago/<id>', views.eliminarPago, name="eliminarPago"),
    path('buscarPago/', views.buscarPago, name="buscarPago"),

   # Evaluación----------------------------------------------------------------------------------------------
    path('evaluaciones/', views.listaEvaluacion, name="listarEvaluaciones"),
    path('formularioEvaluacion/', views.formularioEvaluacion, name="formularioEvaluacion"),
    path('guardarEvaluacion/',views.guardarEvaluacion, name="guardarEvaluacion"),
    path('edicionEvaluacion/<id>', views.edicionEvaluacion, name="edicionEvaluacion"),
    path('editarEvaluacion/', views.editarEvaluacion, name="editarEvaluacion"),
    path('eliminarEvaluacion/<id>', views.eliminarEvaluacion, name="eliminarEvaluacion"),
    path('buscarEvaluacion/', views.buscarEvaluacion, name="buscarEvaluacion"),

   # Garantía-------------------------------------------------------------------------------------------------
   path('garantia/', views.listaGarantia, name="listarGarantias"),
   path('formularioGarantia/', views.formularioGarantia, name="formularioGarantia"),
   path('guardarGarantia/',views.guardarGarantia, name="guardarGarantia"),
   path('edicionGarantia/<id>', views.edicionGarantia, name="edicionGarantia"),
   path('editarGarantia/', views.editarGarantia, name="editarGarantia"),
   path('eliminarGarantia/<id>', views.eliminarGarantia, name="eliminarGarantia"),
   path('buscarGarantia/', views.buscarGarantia, name="buscarGarantia"),
]

geprapapp/models.py
from django.core.serializers import serialize
from django.db import models


class Usuario(models.Model):
    """Módulo que contiene los campos necesarios para los registros de los usuarios
    """
    cedula = models.IntegerField(unique=True)
    nombre = models.CharField(max_length=100)
    telefono = models.IntegerField()
    direccion = models.CharField(max_length=30)
    correo = models.EmailField(max_length=250, unique=True)
    nombreUsuario = models.CharField(max_length=100,  unique=True)
    clave = models.CharField(max_length=254)
    ROLES = (
        ('A', 'Administrador'),
        ('O', 'Operario'),
        ('C', 'Cliente'),
        ('I', 'Instalador')
    )

    rol = models.CharField(max_length=100, choices=ROLES)

    def __str__(self):
        return f"{self.cedula} - {self.nombre}"
    
    def save(self, *args, **kwargs):
        #Cifrado de claves
        from .crypt import claveEncriptada
        
        """if self.clave != "":
            anterior = self.clave
            encriptada = claveEncriptada(kwargs["id_clave"])
            if anterior == encriptada:
                print("Update: permace la misma clave")
            else:
                print("Update:cambio de clave")
                self.clave = claveEncriptada(kwargs["id_clave"])
        else:
            print("nuevo trabajdor")"""
        self.clave = claveEncriptada(self.clave)
        super(Usuario, self).save(*args, **kwargs)

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    desc = models.CharField(max_length=300, null= True, blank=True)
    
    
    class Meta:
        verbose_name= "Categoria"
        verbose_name_plural = "Categorias"

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=100, unique = True)
    descripcion = models.CharField(max_length= 254, null= True, blank=True)
    precio = models.IntegerField()
    categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)
    imagen = models.ImageField(upload_to="tienda", null=True, blank=True)

    def __str__(self):
        return f"{self.nombre}"

class Servicio(models.Model):
    descripcion = models.CharField(max_length=250)

    def __str__(self):
        return f"{self.descripcion}"

class Pedido(models.Model):
    fecha_pedido = models.DateField()
    total = models.IntegerField()
    usuario = models.ForeignKey(Usuario, on_delete = models.DO_NOTHING)
    estado = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.usuario}"

class Detalle_Pedido(models.Model):
    id_pedido = models.ForeignKey(Pedido, on_delete = models.DO_NOTHING)
    id_producto = models.ForeignKey(Producto, null=True, blank=True, on_delete = models.DO_NOTHING )
    id_servicio = models.ForeignKey(Servicio, null=True, blank=True, on_delete = models.DO_NOTHING )
    cantidad = models.IntegerField()
    usuario = models.ForeignKey(Usuario, on_delete = models.DO_NOTHING)

    def __str__(self):
        return f"{self.id_pedido}"

class Agenda(models.Model):
    fecha_asignada = models.DateField()
    pedido = models.ForeignKey(Pedido, on_delete = models.DO_NOTHING)

    def __str__(self):
        return f"{self.fecha_asignada}"

class Metodo_Pago(models.Model):
    metodoPago = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.metodoPago}"

class Pago(models.Model):
    plazos = models.IntegerField()
    pedido = models.ForeignKey(Pedido, on_delete=models.DO_NOTHING)
    formaPago = models.ForeignKey(Metodo_Pago, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f"{self.pedido}"

class Garantia(models.Model):
    descripcion = models.TextField()
    fechaGarantia = models.DateField()
    pedido = models.ForeignKey(Pedido, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f"{self.pedido}"

class Evaluacion(models.Model):
    calificacionEvaluacion = models.TextField()
    comentarios = models.TextField()
    pedido = models.ForeignKey(Pedido, on_delete=models.DO_NOTHING)
    usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f"{self.usuario}"

geprapapp/templates/geprapapp/usuario/edicionUsuario.html
{% extends "geprapapp/base.html" %}
{% load static %}

{% block titulo %} Editar Usuarios {% endblock %}

{% block contenedor %}

<h3 style="text-align: center;">Editar Usuario ( {{ usuario.id }} )</h3>
<br>
<div class="container" style="text-align: center;">
    <form action="{% url 'geprapapp:editarUsuario' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{ usuario.id }}" />
        <label>Cédula</label><br>
        <input type="number" class="form-control" name="cedula" value = "{{ usuario.cedula }}"> <br><br>

        <label>Nombre</label><br>
        <input type="text" class="form-control" name="nombre" value = "{{ usuario.nombre }}"> <br><br>

        <label>Teléfono</label><br>
        <input type="number" class="form-control" name="telefono" value = "{{ usuario.telefono }}"> <br><br>

        <label>Dirección</label><br>
        <input type="text" class="form-control" name="direccion" value = "{{ usuario.direccion }}"> <br><br>

        <label>Correo Electrónico</label><br>
        <input type="email" class="form-control" name="correo" value = "{{ usuario.correo }}"> <br><br>

        <label>Nombre Usuario</label><br>
        <input type="text" class="form-control" name="nombreUsuario" value="{{ usuario.nombreUsuario }}"><br><br>

        <label>Contraseña</label><br>
        <input type="password" class="form-control" name="clave" value="{{ usuario.clave }}"><br><br>

        <label>Rol</label><br>
            <select class="form-control" name="rol">
                <option value="">Seleccione:</option>
                <option value="A" {% if usuario.rol == 'A' %}selected=""{% endif %}>Administrador</option>
                <option value="O" {% if usuario.rol == 'O' %}selected=""{% endif %}>Operario</option>
                <option value="C" {% if usuario.rol == 'C' %}selected=""{% endif %}>Cliente</option>
                <option value="I" {% if usuario.rol == 'I' %}selected=""{% endif %}>Instalador</option>
            </select><br><br>
    
        <button type="submit">Actualizar</button>

    </form>
</div>
{% endblock %}

geprapapp/templates/geprapapp/usuario/listarUsuarioAdmin.html
{% extends "geprapapp/base.html" %}
{% load static %}

{% block titulo %} Listado de Usuarios {% endblock %}

{% block contenedor %}
    <h1> Usuarios </h1>

    <a class="btn btn-warning" href="{% url 'geprapapp:formularioUsuario'%}">Agregar Usuario</a>
    <br>

    {% if datos %} 
    <br>
    <form class="d-flex" role="search" action="{% url 'geprapapp:buscarUsuario' %}" method="post">
      {% csrf_token %}
      <input onkeyup="buscarUsuario('{% url 'geprapapp:buscarUsuario' %}');" class="form-control" type="search" name="buscar" id="buscar">
    </form><br>

    <div id="respuesta">

        <table class="table table-striped" width="100%" border="1">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Cédula</th>
                    <th>Nombre</th>
                    <th>Teléfono</th>
                    <th>Dirección</th>
                    <th>Correo Electrónico</th>
                    <th>Nombre Usuario</th>
                    <th>Contraseña</th>
                    <th>Rol</th>
                    <th>Acción</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
        {% for u in datos %}
            <tr>
                <td>{{ u.id }}</td>
                <td>{{ u.cedula }}</td>
                <td>{{ u.nombre }}</td>
                <td>{{ u.telefono }}</td>
                <td>{{ u.direccion }}</td>
                <td>{{ u.correo }}</td>
                <td>{{ u.nombreUsuario }}</td>
                <td>{{ u.clave }}</td>
                <td>{{ u.get_rol_display }}</td>
                <td><a href="{% url 'geprapapp:edicionUsuario' u.id %}" class="btn btn-info">Editar</a></td>
                <td><a href="/geprapapp/eliminarUsuario/{{u.id}}" class="btn btn-dark">Eliminar</a></td>
            </tr>
        {% endfor %} 
            </tbody>
        </table>

          <p>Página {{ datos.number }} de {{ datos.paginator.num_pages }}.</p>
          
          <nav aria-label="...">
              <ul class="pagination">
                <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
                  <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
                  <a class="page-link" {% if datos.has_previous %}href="?page={{ datos.previous_page_number }}"{% endif %}>Anterior</a>
                </li>
                
                  {% for i in "x"|rjust:datos.paginator.num_pages|make_list %}
                      <li class="page-item {% if forloop.counter == datos.number %}active{% endif %}" aria-current="page">
                          <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                      </li>
                  {% endfor %}

                <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
                  <a class="page-link" {% if datos.has_next %}href="?page={{ datos.next_page_number }}"{% endif %}>Siguiente</a>
                </li>
                <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
                  <a class="page-link" {% if datos.has_next %}href="?page={{ datos.paginator.num_pages }}"{% endif %}>&raquo;</a>
                </li>
              </ul>
          </nav>
    </div>  

    {% else %}
        No hay datos...
    {% endif %}

{% endblock %}

    

geprapapp/templates/geprapapp/usuario/listarUsuarioInstalador.html
{% extends "geprapapp/base.html" %}
{% load static %}

{% block titulo %} Listado de Usuarios {% endblock %}

{% block contenedor %}
    <h1> Usuarios </h1>
    
    {% if datos %} 
    <br>
    <form class="d-flex" role="search" action="{% url 'geprapapp:buscarUsuario' %}" method="post">
      {% csrf_token %}
      <input onkeyup="buscarUsuario('{% url 'geprapapp:buscarUsuario' %}');" class="form-control" type="search" name="buscar" id="buscar">
    </form><br>

    <div id="respuesta">

        <table class="table table-striped" width="100%" border="1">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Cédula</th>
                    <th>Nombre</th>
                    <th>Teléfono</th>
                    <th>Dirección</th>
                    <th>Correo Electrónico</th>
                    <th>Nombre Usuario</th>
                    <th>Contraseña</th>
                    <th>Rol</th>
                </tr>
            </thead>
            <tbody>
        {% for u in datos %}
            <tr>
                <td>{{ u.id }}</td>
                <td>{{ u.cedula }}</td>
                <td>{{ u.nombre }}</td>
                <td>{{ u.telefono }}</td>
                <td>{{ u.direccion }}</td>
                <td>{{ u.correo }}</td>
                <td>{{ u.nombreUsuario }}</td>
                <td>{{ u.clave }}</td>
                <td>{{ u.get_rol_display }}</td>
            </tr>
        {% endfor %} 
            </tbody>
        </table>

          <p>Página {{ datos.number }} de {{ datos.paginator.num_pages }}.</p>
          
          <nav aria-label="...">
              <ul class="pagination">
                <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
                  <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
                  <a class="page-link" {% if datos.has_previous %}href="?page={{ datos.previous_page_number }}"{% endif %}>Anterior</a>
                </li>
                
                  {% for i in "x"|rjust:datos.paginator.num_pages|make_list %}
                      <li class="page-item {% if forloop.counter == datos.number %}active{% endif %}" aria-current="page">
                          <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                      </li>
                  {% endfor %}

                <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
                  <a class="page-link" {% if datos.has_next %}href="?page={{ datos.next_page_number }}"{% endif %}>Siguiente</a>
                </li>
                <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
                  <a class="page-link" {% if datos.has_next %}href="?page={{ datos.paginator.num_pages }}"{% endif %}>&raquo;</a>
                </li>
              </ul>
          </nav>
    </div>  
    {% else %}
        No hay datos...
    {% endif %}

{% endblock %}

geprapapp/templates/geprapapp/usuario/listarUsuarios.html
{% extends "geprapapp/base.html" %}
{% load static %}

{% block titulo %} Listado de Usuarios {% endblock %}

{% block contenedor %}
    <h1>Mis datos</h1>
    <br>
    {% if datos %} 
    <br>
  
    <div id="respuesta">

        <table class="table table-striped" width="100%" border="1">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Cédula</th>
                    <th>Nombre</th>
                    <th>Teléfono</th>
                    <th>Dirección</th>
                    <th>Correo Electrónico</th>
                    <th>Nombre Usuario</th>
                    <th>Contraseña</th>
                    <th>Rol</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
        {% for u in datos %}
            <tr>
                <td>{{ u.id }}</td>
                <td>{{ u.cedula }}</td>
                <td>{{ u.nombre }}</td>
                <td>{{ u.telefono }}</td>
                <td>{{ u.direccion }}</td>
                <td>{{ u.correo }}</td>
                <td>{{ u.nombreUsuario }}</td>
                <td>{{ u.clave }}</td>
                <td>{{ u.get_rol_display }}</td>
                <td><a href="{% url 'geprapapp:edicionUsuario' u.id %}" class="btn btn-info">Editar</a></td>
            </tr>
        {% endfor %} 
            </tbody>
        </table>

        {% if datos > 1 %}
          <p>Página {{ datos.number }} de {{ datos.paginator.num_pages }}.</p>
          
          <nav aria-label="...">
              <ul class="pagination">
                <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
                  <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
                  <a class="page-link" {% if datos.has_previous %}href="?page={{ datos.previous_page_number }}"{% endif %}>Anterior</a>
                </li>
                
                  {% for i in "x"|rjust:datos.paginator.num_pages|make_list %}
                      <li class="page-item {% if forloop.counter == datos.number %}active{% endif %}" aria-current="page">
                          <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                      </li>
                  {% endfor %}

                <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
                  <a class="page-link" {% if datos.has_next %}href="?page={{ datos.next_page_number }}"{% endif %}>Siguiente</a>
                </li>
                <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
                  <a class="page-link" {% if datos.has_next %}href="?page={{ datos.paginator.num_pages }}"{% endif %}>&raquo;</a>
                </li>
              </ul>
          </nav>
          {% endif %}

    </div>  

    {% else %}
        No hay datos...
    {% endif %}

{% endblock %}

    

geprapapp/templates/geprapapp/usuario/listar_usuario_ajax.html
{% extends "geprapapp/base2.html" %}
{% load static %}

{% block contenedor %}
 
    {% if datos %} 
    <br><br>

        <table class="table table-striped" width="100%" border="1">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Cédula</th>
                    <th>Nombre</th>
                    <th>Teléfono</th>
                    <th>Dirección</th>
                    <th>Correo Electrónico</th>
                    <th>Nombre de Usuario</th>
                    <th>Contraseña</th>
                    <th>Rol</th>
                    <th>Acción</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
        {% for u in datos %}
            <tr>
                <td>{{ u.id }}</td>
                <td>{{ u.cedula }}</td>
                <td>{{ u.nombre }}</td>
                <td>{{ u.telefono }}</td>
                <td>{{ u.direccion }}</td>
                <td>{{ u.correo }}</td>
                <td>{{ u.nombreUsuario }}</td>
                <td>{{ u.clave }}</td>
                <td>{{ u.get_rol_display }}</td>
                <td><a href="{% url 'geprapapp:edicionUsuario' u.id %}" class="btn btn-info">Editar</a></td>
                <td><a href="/geprapapp/eliminarUsuario/{{u.id}}" class="btn btn-dark">Eliminar</a></td>
            </tr>
        {% endfor %} 
            </tbody>
        </table>

        <p>Página {{ datos.number }} de {{ datos.paginator.num_pages }}.</p>
        
        <nav aria-label="...">
            <ul class="pagination">
              <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
                <a class="page-link" href="?page=1">&laquo;</a>
              </li>
              <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
                <a class="page-link" {% if datos.has_previous %}href="?page={{ datos.previous_page_number }}"{% endif %}>Anterior</a>
              </li>
              
                {% for i in "x"|rjust:datos.paginator.num_pages|make_list %}
                    <li class="page-item {% if forloop.counter == datos.number %}active{% endif %}" aria-current="page">
                        <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                    </li>
                {% endfor %}

              <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
                <a class="page-link" {% if datos.has_next %}href="?page={{ datos.next_page_number }}"{% endif %}>Siguiente</a>
              </li>
              <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
                <a class="page-link" {% if datos.has_next %}href="?page={{ datos.paginator.num_pages }}"{% endif %}>&raquo;</a>
              </li>
            </ul>
          </nav>
    </div>  

    {% else %}
        No hay datos...
    {% endif %}

{% endblock %}

    

geprapapp/templates/geprapapp/usuario/nuevoUsuario.html
{% extends "geprapapp/base.html" %}
{% load static %}

{% block contenedor %}
<h3 style="text-align: center">Agregar Usuario</h3>
<br>

<div class="container" style="text-align: center;">
    <form action="{% url 'geprapapp:guardarUsuario' %}" method="post">
        {% csrf_token %}
        <label>Cédula</label><br>
        <input type="number" class="form-control" name="cedula" id=""><br><br> 

        <label>Nombre</label><br>
        <input type="text" class="form-control" name="nombre" id=""><br> <br> 

        <label>Teléfono</label><br>
        <input type="number" class="form-control" name="telefono" id=""><br><br>

        <label>Dirección</label><br>
        <input type="text" class="form-control" name="direccion" id=""><br><br>

        <label>Email</label><br>
        <input type="email" class="form-control"name="correo" id=""><br><br>

        <label>Nombre Usuario</label><br>
        <input type="text" class="form-control" name="nombreUsuario" id=""><br><br>

        <label>Contraseña</label><br>
        <input type="password" class="form-control" name="clave" id=""><br><br>

        <label>Rol</label><br>
        <select  class="form-control" name="rol">
            <option value="">Seleccione:</option>
            <option value="A">Administrador</option>
            <option value="O">Operario</option>
            <option value="C">Cliente</option>
            <option value="I">Instalador</option>
        </select><br><br>

        <button type="submit">Enviar</button>
    </form>
</div>

{% endblock %}