geprap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('geprapapp.urls')),
    path('tienda/', include('tienda.urls')),
    path('carrito/', include('carrito.urls')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

geprapapp/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name= "geprapapp"
urlpatterns = [
    path('', views.index, name = "index"),

    #Login----------------------------------------------------------------------------------------
    path('loginFormulario/', views.loginFormulario, name="loginFormulario" ),
    path('login/', views.login, name="login" ),
    path('logout/', views.logout, name="logout" ),
     
    #Restablecer contraseña------------------------------------------------------------------------
    path('solicitudRestablecer/',views.solicitudRestablecer, name="solicitudRestablecer"),
    path('restablecer/',views.restablecerContrasena, name="restablecerContrasena"), 
    path('restablecerContrasena/<int:id>',views.cambiarContrasena, name="cambiarContrasena"),
    path('cambiarClave/',views.cambiarClave, name="cambiarClave"),

    # Usuarios--------------------------------------------------------------------------------------
    path('usuarios/', views.listaUsuarios, name="listarUsuarios"),
    path('formularioUsuario/', views.formularioUsuario, name="formularioUsuario"),
    path('guardarUsuario/',views.guardarUsuario, name="guardarUsuario"),
    path('edicionUsuario/<id>', views.edicionUsuario,name="edicionUsuario"),
    path('editarUsuario/', views.editarUsuario, name="editarUsuario"),
    path('eliminarUsuario/<id>', views.eliminarUsuario, name="eliminarUsuario"),
    path('buscarUsuario/', views.buscarUsuario, name="buscarUsuario"), 

    #Registrar cliente-------------------------------------------------------------------------------
    path('formularioRegistro/', views.ClienteFormulario, name="formularioRegistro"),
    path('RegistroCliente/',views.RegistroCliente, name="RegistroCliente"),

    # Categoría--------------------------------------------------------------------------------------
    path('categorias/', views.listaCategoria, name="listarCategoria"),
    path('formularioCategoria/', views.formularioCategoria, name="formularioCategoria"),
    path('guardarCategoria/',views.guardarCategoria, name="guardarCategoria"),
    path('edicionCategoria/<id>', views.edicionCategoria, name="edicionCategoria"),
    path('editarCategoria/', views.editarCategoria, name="editarCategoria"),
    path('eliminarCategoria/<id>', views.eliminarCategoria, name="eliminarCategoria"),
    path('buscarCategoria/', views.buscarCategoria, name="buscarCategoria"),

    # Productos----------------------------------------------------------------------------------------
    path('productos/', views.listaProducto, name="listarProductos"),
    path('formularioProducto/', views.formularioProducto, name="formularioProducto"),
    path('guardarProducto/',views.guardarProducto, name="guardarProducto"),
    path('edicionProducto/<id>', views.editarProducto, name="edicionProducto"),
    path('editarProducto/', views.editarProducto, name="editarProducto"),
    path('eliminarProducto/<id>', views.eliminarProducto, name="eliminarProducto"),
    path('buscarProducto/', views.buscarProducto, name="buscarProducto"),
    
    # Servicio------------------------------------------------------------------------------------------
    path('servicios/', views.listaServicio, name="listarServicio"),
    path('formularioServicio/', views.formularioServicio, name="formularioServicio"),
    path('guardarServicio/',views.guardarServicio, name="guardarServicio"),
    path('edicionServicio/<id>', views.edicionServicio, name="edicionServicio"),
    path('editarServicio/', views.editarServicio, name="editarServicio"),
    path('eliminarServicio/<id>', views.eliminarServicio, name="eliminarServicio"),
    path('buscarServicio/', views.buscarServicio, name="buscarServicio"),

    # Pedidos--------------------------------------------------------------------------------------------
    
    
    path('pedidos/', views.listaPedido, name="listarPedidos"),
    path('formularioPedido/', views.formularioPedido, name="formularioPedido"),
    path('guardarPedido/',views.guardarPedido, name="guardarPedido"),
    path('edicionPedido/<id>', views.edicionPedido, name="edicionPedido"),
    path('editarPedido/', views.editarPedido, name="editarPedido"),
    path('eliminarPedido/<id>', views.eliminarPedido, name="eliminarPedido"),
    path('buscarPedido/', views.buscarPedido, name="buscarPedido"),

    # DetallePedidos---------------------------------------------------------------------------------------
    path('DetallePedidos/', views.listaDetallePedido, name="listarDetallePedidos"),
    path('formularioDetallePedido/', views.formularioDetallePedido, name="formularioDetallePedido"),
    path('guardarDetallePedido/',views.guardarDetallePedido, name="guardarDetallePedido"),
    path('edicionDetallePedido/<id>', views.edicionDetallePedido, name="edicionDetallePedido"),
    path('editarDetallePedido/', views.editarDetallePedido, name="editarDetallePedido"),
    path('eliminarDetallePedido/<id>', views.eliminarDetallePedido, name="eliminarDetallePedido"),
    path('buscarDetallePedido/', views.buscarDetallePedido, name="buscarDetallePedido"),

    # Agenda-------------------------------------------------------------------------------------------------
    path('agenda/', views.listaAgenda, name="listarAgenda"),
    path('formularioAgenda/', views.formularioAgenda, name="formularioAgenda"),
    path('guardarAgenda/',views.guardarAgenda, name="guardarAgenda"),
    path('edicionAgenda/<id>', views.edicionAgenda, name="edicionAgenda"),
    path('editarAgenda/', views.editarAgenda, name="editarAgenda"),
    path('eliminarAgenda/<id>', views.eliminarAgenda, name="eliminarAgenda"),
    path('buscarAgenda/', views.buscarAgenda, name="buscarAgenda"),

    # Metodo_Pago--------------------------------------------------------------------------------------------
    path('metodosPago/', views.listaMetodoPago, name="listarMetodoPago"),
    path('formularioMetodoPago/', views.formularioMetodoPago, name="formularioMetodoPago"),
    path('guardarMetodoPago/',views.guardarMetodoPago, name="guardarMetodoPago"),
    path('edicionMetodoPago/<id>', views.edicionMetodoPago, name="edicionMetodoPago"),
    path('editarMetodoPago/', views.editarMetodoPago, name="editarMetodoPago"),
    path('eliminarMetodoPago/<id>', views.eliminarMetodoPago, name="eliminarMetodoPago"),
    path('buscarMetodoPago/', views.buscarMetodoPago, name="buscarMetodoPago"),

    # Pagos--------------------------------------------------------------------------------------------------
    path('pagos/', views.listaPagos, name="listarPagos"),
    path('formularioPagos/', views.formularioPagos, name="formularioPagos"),
    path('guardarPagos/',views.guardarPagos, name="guardarPago"),
    path('edicionPago/<id>', views.edicionPago, name="edicionPago"),
    path('editarPago/', views.editarPago, name="editarPago"),
    path('eliminarPago/<id>', views.eliminarPago, name="eliminarPago"),
    path('buscarPago/', views.buscarPago, name="buscarPago"),

   # Evaluación----------------------------------------------------------------------------------------------
    path('evaluaciones/', views.listaEvaluacion, name="listarEvaluaciones"),
    path('formularioEvaluacion/', views.formularioEvaluacion, name="formularioEvaluacion"),
    path('guardarEvaluacion/',views.guardarEvaluacion, name="guardarEvaluacion"),
    path('edicionEvaluacion/<id>', views.edicionEvaluacion, name="edicionEvaluacion"),
    path('editarEvaluacion/', views.editarEvaluacion, name="editarEvaluacion"),
    path('eliminarEvaluacion/<id>', views.eliminarEvaluacion, name="eliminarEvaluacion"),
    path('buscarEvaluacion/', views.buscarEvaluacion, name="buscarEvaluacion"),

   # Garantía-------------------------------------------------------------------------------------------------
   path('garantia/', views.listaGarantia, name="listarGarantias"),
   path('formularioGarantia/', views.formularioGarantia, name="formularioGarantia"),
   path('guardarGarantia/',views.guardarGarantia, name="guardarGarantia"),
   path('edicionGarantia/<id>', views.edicionGarantia, name="edicionGarantia"),
   path('editarGarantia/', views.editarGarantia, name="editarGarantia"),
   path('eliminarGarantia/<id>', views.eliminarGarantia, name="eliminarGarantia"),
   path('buscarGarantia/', views.buscarGarantia, name="buscarGarantia"),
]

geprapapp/models.py
from django.core.serializers import serialize
from django.db import models


class Usuario(models.Model):
    """Módulo que contiene los campos necesarios para los registros de los usuarios
    """
    cedula = models.IntegerField(unique=True)
    nombre = models.CharField(max_length=100)
    telefono = models.IntegerField()
    direccion = models.CharField(max_length=30)
    correo = models.EmailField(max_length=250, unique=True)
    nombreUsuario = models.CharField(max_length=100,  unique=True)
    clave = models.CharField(max_length=254)
    ROLES = (
        ('A', 'Administrador'),
        ('O', 'Operario'),
        ('C', 'Cliente'),
        ('I', 'Instalador')
    )

    rol = models.CharField(max_length=100, choices=ROLES)

    def __str__(self):
        return f"{self.cedula} - {self.nombre}"
    
    def save(self, *args, **kwargs):
        #Cifrado de claves
        from .crypt import claveEncriptada
        
        """if self.clave != "":
            anterior = self.clave
            encriptada = claveEncriptada(kwargs["id_clave"])
            if anterior == encriptada:
                print("Update: permace la misma clave")
            else:
                print("Update:cambio de clave")
                self.clave = claveEncriptada(kwargs["id_clave"])
        else:
            print("nuevo trabajdor")"""
        self.clave = claveEncriptada(self.clave)
        super(Usuario, self).save(*args, **kwargs)

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    desc = models.CharField(max_length=300, null= True, blank=True)
    
    
    class Meta:
        verbose_name= "Categoria"
        verbose_name_plural = "Categorias"

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=100, unique = True)
    descripcion = models.CharField(max_length= 254, null= True, blank=True)
    precio = models.IntegerField()
    categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)
    imagen = models.ImageField(upload_to="tienda", null=True, blank=True)

    def __str__(self):
        return f"{self.nombre}"

class Servicio(models.Model):
    descripcion = models.CharField(max_length=250)

    def __str__(self):
        return f"{self.descripcion}"

class Pedido(models.Model):
    fecha_pedido = models.DateField()
    total = models.IntegerField()
    usuario = models.ForeignKey(Usuario, on_delete = models.DO_NOTHING)
    estado = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.usuario}"

class Detalle_Pedido(models.Model):
    id_pedido = models.ForeignKey(Pedido, on_delete = models.DO_NOTHING)
    id_producto = models.ForeignKey(Producto, null=True, blank=True, on_delete = models.DO_NOTHING )
    id_servicio = models.ForeignKey(Servicio, null=True, blank=True, on_delete = models.DO_NOTHING )
    cantidad = models.IntegerField()
    usuario = models.ForeignKey(Usuario, on_delete = models.DO_NOTHING)

    def __str__(self):
        return f"{self.id_pedido}"

class Agenda(models.Model):
    fecha_asignada = models.DateField()
    pedido = models.ForeignKey(Pedido, on_delete = models.DO_NOTHING)

    def __str__(self):
        return f"{self.fecha_asignada}"

class Metodo_Pago(models.Model):
    metodoPago = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.metodoPago}"

class Pago(models.Model):
    plazos = models.IntegerField()
    pedido = models.ForeignKey(Pedido, on_delete=models.DO_NOTHING)
    formaPago = models.ForeignKey(Metodo_Pago, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f"{self.pedido}"

class Garantia(models.Model):
    descripcion = models.TextField()
    fechaGarantia = models.DateField()
    pedido = models.ForeignKey(Pedido, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f"{self.pedido}"

class Evaluacion(models.Model):
    calificacionEvaluacion = models.TextField()
    comentarios = models.TextField()
    pedido = models.ForeignKey(Pedido, on_delete=models.DO_NOTHING)
    usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f"{self.usuario}"

geprapapp/templates/geprapapp/producto/edicionProducto.html
{% extends "geprapapp/base.html" %}
{% load static %}

{% block contenedor %}
<h3 style="text-align: center;">Editar Producto</h3>

<div class="container" style="text-align: center;"></div>
    <form action="{% url 'geprapapp:editarProducto' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{ producto.id }}" />

        <label>Nombre</label><br>
        <input type="text" class="form-control" name="nombre" value="{{ producto.nombre }}" /><br><br> 

        <label>Descripción</label><br>
        <input type="text" class="form-control" name="descripcion" value="{{ producto.descripcion }}" /><br><br>

        <label>Precio</label><br>
        <input type="number" class="form-control" name="precio" value="{{ producto.precio }}" /><br><br>

        <label>Categoría</label><br>
        <select class="form-control" name="categoria">
            <option>Seleccione:</option>
            {% for c in cat %}
                <option value="{{ c.id }}" {% if producto.categoria.id == c.id %}selected=""{% endif %}>{{ c.id }} - {{ c.nombre }}</option>
            {% endfor %}
        </select><br><br>

        <button type="submit">Actualizar</button>
     </form>

{% endblock %}

geprapapp/templates/geprapapp/producto/listarProducto.html
{% extends "geprapapp/base.html" %}
{% load static %}

{% block titulo %} Listado de Productos {% endblock %}

{% block contenedor %}
    <h1> Productos </h1>

    <a class="btn btn-warning" href="{% url 'geprapapp:formularioProducto' %}">Agregar Producto</a><br>

    {% if datos %}
    <br> 

    <form class="d-flex" role="search" action="{% url 'geprapapp:buscarProducto' %}" method="post">
      {% csrf_token %}
      <input onkeyup="buscarProducto('{% url 'geprapapp:buscarProducto' %}');" class="form-control" type="search" name="buscar" id="buscar">
    </form><br>

    <div id="respuesta">
      
        <table class="table table-striped" width="100%" border="1">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Precio</th>
                    <th>Categoría</th>
                    <th>Acción</th>
                    <th>Acción</th>
                    
                </tr>
            </thead>
            <tbody>
        {% for p in datos %}
            <tr>
                <td>{{ p.id }}</td>
                <td>{{ p.nombre }}</td>
                <td>{{ p.descripcion }}</td>
                <td>{{ p.precio }}</td>
                <td>{{ p.categoria }}</td><td><a href="{% url 'geprapapp:editarProducto' p.id %}" class="btn btn-info">Editar</a></td>
                <td><a href="/geprapapp/eliminarProducto/{{p.id}}" class="btn btn-dark">Eliminar</a></td>
            </tr>
        {% endfor %} 
            </tbody>
        </table>

        <p>Página {{ datos.number }} de {{ datos.paginator.num_pages }}.</p>
        
        <nav aria-label="...">
            <ul class="pagination">
              <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
                <a class="page-link" href="?page=1">&laquo;</a>
              </li>
              <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
                <a class="page-link" {% if datos.has_previous %}href="?page={{ datos.previous_page_number }}"{% endif %}>Anterior</a>
              </li>
              
                {% for i in "x"|rjust:datos.paginator.num_pages|make_list %}
                    <li class="page-item {% if forloop.counter == datos.number %}active{% endif %}" aria-current="page">
                        <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                    </li>
                {% endfor %}

              <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
                <a class="page-link" {% if datos.has_next %}href="?page={{ datos.next_page_number }}"{% endif %}>Siguiente</a>
              </li>
              <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
                <a class="page-link" {% if datos.has_next %}href="?page={{ datos.paginator.num_pages }}"{% endif %}>&raquo;</a>
              </li>
            </ul>
          </nav>
        </div>  

    {% else %} 
        no hay datos 
    {% endif %} 

{% endblock %}

    

geprapapp/templates/geprapapp/producto/listar_producto_ajax.html
{% extends "geprapapp/base2.html" %}
{% load static %}

{% block contenedor %}
    
    {% if datos %}
    <br> 
        <table class="table table-striped" width="100%" border="1">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Precio</th>
                    <th>Categoría</th>
                    <th>Acción</th>
                    <th>Acción</th>
                    
                </tr>
            </thead>
            <tbody>
        {% for p in datos %}
            <tr>
                <td>{{ p.id }}</td>
                <td>{{ p.nombre }}</td>
                <td>{{ p.descripcion }}</td>
                <td>{{ p.precio }}</td>
                <td>{{ p.categoria }}</td>
                <td><a href="{% url 'geprapapp:edicionProducto' p.id %}" class="btn btn-info">Editar</a></td>
                <td><a href="/geprapapp/eliminarProducto/{{p.id}}" class="btn btn-dark">Eliminar</a></td>
            </tr>
        {% endfor %} 
            </tbody>
        </table>

        <p>Página {{ datos.number }} de {{ datos.paginator.num_pages }}.</p>
        
        <nav aria-label="...">
            <ul class="pagination">
              <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
                <a class="page-link" href="?page=1">&laquo;</a>
              </li>
              <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
                <a class="page-link" {% if datos.has_previous %}href="?page={{ datos.previous_page_number }}"{% endif %}>Anterior</a>
              </li>
              
                {% for i in "x"|rjust:datos.paginator.num_pages|make_list %}
                    <li class="page-item {% if forloop.counter == datos.number %}active{% endif %}" aria-current="page">
                        <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                    </li>
                {% endfor %}

              <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
                <a class="page-link" {% if datos.has_next %}href="?page={{ datos.next_page_number }}"{% endif %}>Siguiente</a>
              </li>
              <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
                <a class="page-link" {% if datos.has_next %}href="?page={{ datos.paginator.num_pages }}"{% endif %}>&raquo;</a>
              </li>
            </ul>
          </nav>
        </div>  

    {% else %} 
        no hay datos 
    {% endif %} 

{% endblock %}

    

geprapapp/templates/geprapapp/producto/nuevoProducto.html
{% extends "geprapapp/base.html" %}
{% load static %}

{% block contenedor %}
<h3 style="text-align: center">Agregar Producto</h3>
<br>

<div class="container" style="text-align: center;">
    <form action="{% url 'geprapapp:guardarProducto' %}" method="post">
        {% csrf_token %}
        <label>Nombre</label><br>
        <input type="text" class="form-control" name="nombre" id=""><br>  

        <label>Descripción</label><br>
        <input type="text" class="form-control" name="descripcion" id=""><br>

        <label>Precio</label><br>
        <input type="number" class="form-control" name="precio" id=""><br><br>

        <label>Imagen</label><br>
        <input type="file" class="form-control" name="imagen" id=""><br><br>

        <label>Categoría</label><br>
        <select class="form-control" name="categoria">
            <option>Seleccione:</option>
            {% for c in cat %}
                <option value="{{ c.id }}">{{ c.nombre }}</option>
            {% endfor %}
        </select><br><br>

        <button type="submit">Enviar</button>
    </form>
</div>
{% endblock %}